version = 0.1
[default]
[default.global]
[default.global.parameters]
stack_name = "agent-builder-sam-dev"
s3_bucket = ""
s3_prefix = "agent-builder-dev"
region = "us-east-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = [
    "Environment=dev"
]
tags = "Environment=development project=agent-builder"

[default.build]
[default.build.parameters]
cached = true
parallel = true
use_container = true

[default.deploy]
[default.deploy.parameters]
stack_name = "agent-builder-sam-dev"
s3_bucket = ""
s3_prefix = "agent-builder-dev"
region = "us-east-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = [
    "Environment=dev"
]
tags = "Environment=development project=agent-builder"
fail_on_empty_changeset = false