AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: "Agent Builder - Database Stack (DynamoDB Tables)"

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues: [dev, staging, prod]

Resources:
  # Users Table
  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub agent-builder-users-${Environment}
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true

  # Projects Table
  ProjectsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub agent-builder-projects-${Environment}
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: userId
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: UserIndex
          KeySchema:
            - AttributeName: userId
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true

  # Tasks Table
  TasksTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub agent-builder-tasks-${Environment}
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: projectId
          AttributeType: S
        - AttributeName: taskId
          AttributeType: S
      KeySchema:
        - AttributeName: projectId
          KeyType: HASH
        - AttributeName: taskId
          KeyType: RANGE
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true

  # Artifacts Table
  ArtifactsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub agent-builder-artifacts-${Environment}
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: projectId
          AttributeType: S
        - AttributeName: artifactId
          AttributeType: S
      KeySchema:
        - AttributeName: projectId
          KeyType: HASH
        - AttributeName: artifactId
          KeyType: RANGE
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true

  # WebSocket Connections Table
  ConnectionsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub agent-builder-connections-${Environment}
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: connectionId
          AttributeType: S
        - AttributeName: projectId
          AttributeType: S
      KeySchema:
        - AttributeName: connectionId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: ProjectIndex
          KeySchema:
            - AttributeName: projectId
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true

Outputs:
  UsersTableName:
    Description: "Name of the Users DynamoDB table"
    Value: !Ref UsersTable
    Export:
      Name: !Sub ${AWS::StackName}-UsersTable

  ProjectsTableName:
    Description: "Name of the Projects DynamoDB table"
    Value: !Ref ProjectsTable
    Export:
      Name: !Sub ${AWS::StackName}-ProjectsTable

  TasksTableName:
    Description: "Name of the Tasks DynamoDB table"
    Value: !Ref TasksTable
    Export:
      Name: !Sub ${AWS::StackName}-TasksTable

  ArtifactsTableName:
    Description: "Name of the Artifacts DynamoDB table"
    Value: !Ref ArtifactsTable
    Export:
      Name: !Sub ${AWS::StackName}-ArtifactsTable

  ConnectionsTableName:
    Description: "Name of the Connections DynamoDB table"
    Value: !Ref ConnectionsTable
    Export:
      Name: !Sub ${AWS::StackName}-ConnectionsTable